shoulder_pan_joint: -1.34390
shoulder_lift_joint: -1.51844
elbow_joint: 1.39626
wrist_1_joint: 3.22886
wrist_2_joint: -1.74533
wrist_3_joint: 3.14159


#shoulder_pan_joint: 0.0
#shoulder_lift_joint: -2.39
#elbow_joint: 2.4
#wrist_1_joint: -3.15
#wrist_2_joint: -1.58
#wrist_3_joint: 3.15

